//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordenada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coordenada()
        {
            this.Micro = new HashSet<Micro>();
            this.Paradero = new HashSet<Paradero>();
        }
    
        public int Id { get; set; }
        public int Orden { get; set; }
        public double Latitud { get; set; }
        public double Longitud { get; set; }
        public Nullable<int> Ruta_Id { get; set; }
    
        public virtual Ruta Ruta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Micro> Micro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paradero> Paradero { get; set; }
    }
}
