//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialDiario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HistorialDiario()
        {
            this.HistorialIdaVuelta = new HashSet<HistorialIdaVuelta>();
        }
    
        public int Id { get; set; }
        public string NombreChofer { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public System.DateTime HoraFinal { get; set; }
        public float KilometrosRecorridos { get; set; }
        public int CalificacionesRecibidas { get; set; }
        public float CalificacionDiaria { get; set; }
        public int PasajerosTransportados { get; set; }
        public int NumeroIdaVueltas { get; set; }
        public int IdMicro { get; set; }
    
        public virtual Micro Micro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialIdaVuelta> HistorialIdaVuelta { get; set; }
    }
}
