//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialParadero
    {
        public int Id { get; set; }
        public System.DateTime HoraLlegada { get; set; }
        public System.TimeSpan TiempoDetenido { get; set; }
        public int PasajerosRecibidos { get; set; }
        public int IdIdaVuelta { get; set; }
    
        public virtual HistorialIdaVuelta HistorialIdaVuelta { get; set; }
    }
}
