//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioParadero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioParadero()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public double DistanciaEntre { get; set; }
        public int ParaderoId { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Paradero Paradero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
