//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialIdaVuelta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HistorialIdaVuelta()
        {
            this.HistorialParadero = new HashSet<HistorialParadero>();
        }
    
        public int Id { get; set; }
        public int PasajerosTransportados { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public System.DateTime HoraTermino { get; set; }
        public System.TimeSpan DuracionRecorrido { get; set; }
        public int IdDiario { get; set; }
    
        public virtual HistorialDiario HistorialDiario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialParadero> HistorialParadero { get; set; }
    }
}
