//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MicroParadero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MicroParadero()
        {
            this.Micro = new HashSet<Micro>();
        }
    
        public int Id { get; set; }
        public double DistanciaEntre { get; set; }
        public int ParaderoId { get; set; }
        public int MicroId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Micro> Micro { get; set; }
        public virtual Micro Micro1 { get; set; }
        public virtual Paradero Paradero { get; set; }
    }
}
