//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Micro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Micro()
        {
            this.MicroChofer1 = new HashSet<MicroChofer>();
            this.MicroParadero1 = new HashSet<MicroParadero>();
        }
    
        public int Id { get; set; }
        public string Patente { get; set; }
        public int Calificacion { get; set; }
        public Nullable<int> LineaId { get; set; }
        public Nullable<int> MicroParaderoId { get; set; }
        public Nullable<int> MicroChoferId { get; set; }
    
        public virtual Linea Linea { get; set; }
        public virtual MicroChofer MicroChofer { get; set; }
        public virtual MicroParadero MicroParadero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MicroChofer> MicroChofer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MicroParadero> MicroParadero1 { get; set; }
    }
}
