//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MicroSystemDBEntities10 : DbContext
    {
        public MicroSystemDBEntities10()
            : base("name=MicroSystemDBEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coordenada> Coordenada { get; set; }
        public virtual DbSet<HistorialDiario> HistorialDiario { get; set; }
        public virtual DbSet<HistorialIdaVuelta> HistorialIdaVuelta { get; set; }
        public virtual DbSet<HistorialParadero> HistorialParadero { get; set; }
        public virtual DbSet<Linea> Linea { get; set; }
        public virtual DbSet<Micro> Micro { get; set; }
        public virtual DbSet<MicroChofer> MicroChofer { get; set; }
        public virtual DbSet<MicroParadero> MicroParadero { get; set; }
        public virtual DbSet<MicroPasajero> MicroPasajero { get; set; }
        public virtual DbSet<Paradero> Paradero { get; set; }
        public virtual DbSet<Ruta> Ruta { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioParadero> UsuarioParadero { get; set; }
    }
}
