//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.MicroChofer = new HashSet<MicroChofer>();
            this.UsuarioParadero1 = new HashSet<UsuarioParadero>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int Rol { get; set; }
        public double Latitud { get; set; }
        public double Longitud { get; set; }
        public Nullable<int> UsuarioParaderoId { get; set; }
        public Nullable<int> MicroChoferId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MicroChofer> MicroChofer { get; set; }
        public virtual MicroChofer MicroChofer1 { get; set; }
        public virtual UsuarioParadero UsuarioParadero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioParadero> UsuarioParadero1 { get; set; }
    }
}
